package com.pillora.pillora.model

import com.google.firebase.firestore.PropertyName

/**
 * Data class representing a medical consultation.
 *
 * @property id Unique identifier (automatically generated by Firestore).
 * @property userId ID of the user who owns this consultation record.
 * @property specialty Medical specialty (e.g., Cardiology, Ophthalmology).
 * @property doctorName Name of the doctor.
 * @property dateTime Date and time of the consultation (Stored as String, e.g., "dd/MM/yyyy HH:mm").
 * @property location Location of the consultation (clinic name or address).
 * @property observations Additional notes or observations about the consultation.
 * @property patientName Name of the patient for whom the consultation is scheduled.
 * @property isActive Flag to indicate if the consultation is active (for free plan limits).
 * @property isSilencioso Flag to indicate if the consultation alarm is silent.
 * @property toqueAlarmeUri URI for custom alarm sound.
 */
data class Consultation(
    val id: String = "",
    val userId: String = "",
    val specialty: String = "",
    val doctorName: String = "",
    val dateTime: String = "",
    val location: String = "",
    val observations: String = "",
    val patientName: String = "",

    @get:PropertyName("isSilencioso")
    @set:PropertyName("isSilencioso")
    var isSilencioso: Boolean = false,

    val toqueAlarmeUri: String? = null,

    @get:PropertyName("isActive")
    @set:PropertyName("isActive")
    var isActive: Boolean = true
)
