package com.pillora.pillora.model

import com.google.firebase.firestore.DocumentId

/**
 * Data class representing a medical consultation.
 *
 * @property id Unique identifier (automatically generated by Firestore).
 * @property userId ID of the user who owns this consultation record.
 * @property recipientName Name of for whom is the consultation (main user or dependent).
 * @property recipientId ID of the main user or dependent.
 * @property specialty Medical specialty (e.g., Cardiology, Ophthalmology).
 * @property doctorName Name of the doctor.
 * @property dateTime Date and time of the consultation (Stored as String, e.g., "dd/MM/yyyy HH:mm").
 * @property location Location of the consultation (clinic name or address).
 * @property observations Additional notes or observations about the consultation.
 */
data class Consultation(
    @DocumentId val id: String = "",
    val userId: String = "",
    val recipientName: String = "",
    val recipientId: String = "",
    val specialty: String = "",
    val doctorName: String = "",
    val dateTime: String = "", // Consider using Timestamp for Firestore sorting/querying later
    val location: String = "",
    val observations: String = ""
)

