package com.pillora.pillora.model

import com.google.firebase.firestore.DocumentId

/**
 * Data class representing a medical consultation.
 *
 * @property id Unique identifier (automatically generated by Firestore).
 * @property userId ID of the user who owns this consultation record.
 * @property specialty Medical specialty (e.g., Cardiology, Ophthalmology).
 * @property doctorName Name of the doctor.
 * @property dateTime Date and time of the consultation (Stored as String, e.g., "dd/MM/yyyy HH:mm").
 * @property location Location of the consultation (clinic name or address).
 * @property observations Additional notes or observations about the consultation.
 * @property patientName Name of the patient for whom the consultation is scheduled. // Added patientName field
 * @property isActive Flag to indicate if the consultation is active (for free plan limits).
 */
data class Consultation(
    val id: String = "",
    val userId: String = "",
    val specialty: String = "",
    val doctorName: String = "",
    val dateTime: String = "", // Consider using Timestamp for Firestore sorting/querying later
    val location: String = "",
    val observations: String = "",
    val patientName: String = "", // Added patientName fiel
    val isSilencioso: Boolean = false,   // NOVO
    val toqueAlarmeUri: String? = null,   // NOVO
    val isActive: Boolean = true // NOVO: Flag para controlar se a consulta está ativa (para limites do plano Free)
)
